site_name: Imperial College London Christian Postgraduate Group (ICPG)

theme:
  name: material
  palette:
    primary: blue

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
